adjust blog theme second

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -30,7 +30,13 @@ jobs:
       - name: Get pnpm store directory
         id: pnpm-cache
         run: |
-          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
+          set -e
+          pnpm_cache_dir="$(pnpm store path)"
+          if [ $? -ne 0 ]; then
+            echo "Failed to get pnpm cache directory." >&2
+            exit 1
+          fi
+          echo "PNPM_CACHE_DIR=$pnpm_cache_dir" >> $GITHUB_ENV
 
       - uses: actions/cache@v3
         name: Setup pnpm cache
